### ISSUE TITLE
Performance Update

### ISSUE THREAD

**Issue by thorjeus** [tw7613781/daxiang_trade#5]
Hi Dev,

Nice to see RSI strat is available now. 
I saw the demo link, the performance is very good now, may i know what's the settings for that?

Thanks & Regards.

**Comment by tw7613781** [comment]
Actually the performance is bad, it was good for a certain period. So don't invest real money with the strat. The settings is as below.

SYMBOL = "XBTUSD"
BIN_SIZE = "1h"
INTERVAL = {
    '1m': 1 * 60,
    '5m': 5 * 60,
    '1h': 60 * 60,
    '1d': 24 * 60 * 60
    }
LEVERAGE= 5
RATE = 0.5
